# docker-compose.yaml
version: "3.7"

networks:
  team-1-network:

services:
  #Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: ${JENKINS_USER}
    container_name: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8086:50000
      - 8087:8080
    networks:
      - team-1-network
    restart: on-failure
    
  #Sonatype/Nexus
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8088:8081
    networks:
      - team-1-network
    restart: on-failure

volumes:
  nexus-data:
  jenkins_data: